services:
    Spipu\ApiPartnerBundle\:
        resource: '../src/*'
        exclude: '../src/{Entity,Model,SpipuApiPartnerBundle.php}'
        autowire: true
        autoconfigure: true

    Spipu\ApiPartnerBundle\Service\RouteService:
        autowire: true
        arguments:
            $routes: !tagged_iterator 'spipu.api-partner.route'

    Spipu\ApiPartnerBundle\Service\ApiService:
        autowire: true
        arguments:
            $container: '@service_container'
