# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
services:
    Spipu\ApiPartnerBundle\:
        resource: '../src/*'
        exclude: '../src/{Entity,Model,SpipuApiPartnerBundle.php}'
        autowire: true
        autoconfigure: true

    Spipu\ApiPartnerBundle\Service\RouteService:
        autowire: true
        arguments:
            $routes: !tagged_iterator 'spipu.api-partner.route'

    Spipu\ApiPartnerBundle\Service\ApiService:
        autowire: true
        arguments:
            $container: '@service_container'
